apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-sts
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates: [] # This is empty because we're not using it
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
