apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: openshift-gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: thin-csi
