apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
      volume.kubernetes.io/selected-node: disharma-zhg8j-master-0
      volume.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
    creationTimestamp: "2024-12-10T05:04:07Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgresql
    name: data-postgresql-sts-0
    namespace: openshift-gitops
    resourceVersion: "301998201"
    uid: 50fd6c46-5c83-494d-97c1-ad6740db6566
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: thin-csi
    volumeMode: Filesystem
    volumeName: pvc-50fd6c46-5c83-494d-97c1-ad6740db6566
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
